chore: write tests for theme utils
rmwc/rmwc pull request #1204
Opened 2023-11-28 14:25 UTC by EmiBemi

2023-11-28 18:44 UTC, jensborch requested changes

2023-11-28 18:44 UTC, jensborch commented on packages/theme/src/lib/utils.tsx
> +  var a = [r, g, b].map(function (v) {
Can't we use "let" her?

2023-11-28 18:46 UTC, jensborch requested changes

2023-11-28 18:46 UTC, jensborch commented on packages/base/src/lib/utils/strings.tsx
> +    .replace(/(^[a-z]+|[A-Z][a-z]*|[0-9]+)/g, ($1) => '-' + $1.toLowerCase())
We can use `\d` instead of `[0-9]`

2023-11-29 07:13 UTC, EmiBemi commented on packages/base/src/lib/utils/strings.tsx
> +    .replace(/(^[a-z]+|[A-Z][a-z]*|[0-9]+)/g, ($1) => '-' + $1.toLowerCase())
That works too.

2023-11-29 07:14 UTC, EmiBemi commented on packages/theme/src/lib/utils.tsx
> +  var a = [r, g, b].map(function (v) {
Sure

2023-11-30 10:43 UTC, merged